version: 2.1

orbs:
  node: circleci/node@4.1
  puppeteer: threetreeslight/puppeteer@0.1.2

jobs:
  run-tests:
    environment:
      NODE_ENV: development
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - node/install-packages
      - puppeteer/install
      - run:
          name: Run tests
          command: npm test

workflows:
  test: 
    jobs:
      - run-tests
