name: 'Test'
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    name: 'Run Tests 🧪'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Setup Node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: '16.x'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install and build
        run: |
          npm ci
      - name: Run Jest
        run: npm run test
